### ISSUE TITLE
document the origin configurations in README

### ISSUE THREAD

**Issue by ghost** [voxpupuli/puppet-unattended_upgrades#105]
Hi,

I am playing around with your module. It's nice but I am missing deeper origin configuration options.

E.g. we often have the following configuration

```
"origin=Debian,n=oldstable";
"origin=Debian,n=oldstable-updates";
"origin=Debian,n=oldstable-proposed-updates";
"origin=Debian,n=oldstable,l=Debian-Security";
```
So it's nice that it is possible to activate the Security origin by default but what if I want the other origins, too?

How does the origin parameter works? The documentation isn't very verbose about it.

Additionally it would be great if it would be possible to activate the other three with Boolean parameters as well. 

So I wouldn't be forced to use hard coded strings for different distributions.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
- Distribution: Debian 8
- Module version: newest

**Comment by cristianbalan** [comment]
Exactly, can't figure out how to declare the origins.

**Comment by tkoeck** [comment]
Got it, you have to setup the origins array like that

    origins   => [
      "origin=Debian,n=oldstable",
      "origin=Debian,n=oldstable-updates",
      "origin=Debian,n=oldstable-proposed-updates",
      "origin=Debian,n=oldstable,l=Debian-Security",
    ]

but in that case you have to check which distribution you'll use first.

**Comment by ekohl** [comment]
I'd be great if someone could add this to ```README.md```.

**Comment by fetzerms** [comment]
Is there a "proper" way to simply append an origin to the default ones?

**Comment by vegaaz** [comment]
> Is there a "proper" way to simply append an origin to the default ones?

I guess the parameter 'extra_origins' (Array) will satisfy your needs.
In my case I used this:
``
  class { 'unattended_upgrades':
    extra_origins        => [
      '${distro_id}ESM:${distro_codename}',         #lint:ignore:single_quote_string_with_variables
      '${distro_id}:${distro_codename}-updates',    #lint:ignore:single_quote_string_with_variables
    ]
  }
