### ISSUE TITLE
Support Remove-New-Unused-Dependencies

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-unattended_upgrades#106]
According to the ubuntu docs there is a new feature since 16.04 which allows to remove unused dependencies caused by the upgrade.

https://help.ubuntu.com/community/RemoveOldKernels#Configure_Unattended_Upgrades_to_Remove_Unneeded_Kernels_Automatically

That would be very welcome.

**Comment by bastelfreak** [comment]
Hi @hboetes. This is a good idea. Are you able to provide a patch for this?

**Comment by hboetes** [comment]
Hello Tim. Thank you, but I'm way too busy at the moment.
