### ISSUE TITLE
Allowed-Origins contains ${distro_id}:${distro_codename}

### ISSUE THREAD

**Issue by bittner** [voxpupuli/puppet-unattended_upgrades#107]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: 2.3.3
- Distribution: Ubuntu 17.04 Zesty
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)

FILE: `site/profile/manifests/base.pp`
```puppet
# Base profile (includes component modules for all nodes)
class profile::base {
  include unattended_upgrades

  # (... unrelated package and service declaration here ...)
}
```

## What are you seeing

After puppet agent has run on the target machine the `unattended_upgrades` configuration contains the following:

FILE: `/etc/apt/apt.conf.d/50unattended-upgrades`
```apache
// This file is managed by Puppet. DO NOT EDIT.
// Automatically upgrade packages from these (origin:archive) pairs
//
// Note that in Ubuntu security updates may pull in new dependencies
// from non-security sources (e.g. chromium). By allowing the release
// pocket these get automatically pulled in.
Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
};

// List of packages to not update (regexp are supported)
Unattended-Upgrade::Package-Blacklist {
};

// This option allows you to control if on a unclean dpkg exit
// unattended-upgrades will automatically run
//   dpkg --force-confold --configure -a
// The default is true, to ensure updates keep getting installed
Unattended-Upgrade::AutoFixInterruptedDpkg "true";

// Split the upgrade into the smallest possible chunks so that
// they can be interrupted with SIGUSR1. This makes the upgrade
// a bit slower but it has the benefit that shutdown while a upgrade
// is running is possible (with a small delay)
Unattended-Upgrade::MinimalSteps "true";

// Install all unattended-upgrades when the machine is shuting down
// instead of doing it in the background while the machine is running
// This will (obviously) make shutdown slower
Unattended-Upgrade::InstallOnShutdown "false";


// Do automatic removal of new unused dependencies after the upgrade
// (equivalent to apt-get autoremove)
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot *WITHOUT CONFIRMATION*
// if the file /var/run/reboot-required is found after the upgrade
Unattended-Upgrade::Automatic-Reboot "false";

// If automatic reboot is enabled and needed, reboot at the specific
// time instead of immediately
//  Default: "now"
Unattended-Upgrade::Automatic-Reboot-Time "now";

```

## What behaviour did you expect instead

The `Allowed-Origins` section should look like this:

```apache
Unattended-Upgrade::Allowed-Origins {
        "Ubuntu:zesty";
        "Ubuntu:zesty-security";
};
```

## Output log

```bash
$ puppet --version
4.8.2
$ facter --version
2.4.6
$ facter | grep dist
lsbdistcodename => zesty
lsbdistdescription => Ubuntu 17.04
lsbdistid => Ubuntu
lsbdistrelease => 17.04
lsbmajdistrelease => 17.04
os => {"name"=>"Ubuntu", "family"=>"Debian", "release"=>{"major"=>"17.04", "full"=>"17.04"}, "lsb"=>{"distcodename"=>"zesty", "distid"=>"Ubuntu", "distdescription"=>"Ubuntu 17.04", "distrelease"=>"17.04", "majdistrelease"=>"17.04"}}
$ 
```

## Any additional information you'd like to impart

It looks like the variables `${distro_id}` and `${distro_codename}` are encapsulated in `${os}` on our Ubuntu system.

**Comment by bittner** [comment]
Can anyone confirm this is a real issue (and not a configuration mistake)?

Can anyone give hints on how to fix the issue? I'd readily place a PR.

**Comment by bittner** [comment]
Anyone monitoring this repo? :worried:

**Comment by ekohl** [comment]
After reading https://github.com/voxpupuli/puppet-unattended_upgrades/blob/master/manifests/params.pp this looks intended and the history suggests this is a long time practice.

**Comment by bittner** [comment]
No, but seriously, a string `"${distro_id}:${distro_codename}"` in a generated configuration file must be something that is broken. [The placeholders](https://github.com/voxpupuli/puppet-unattended_upgrades/blob/master/manifests/params.pp#L97-L100) are maybe meant to be replaced later in the setup process, or so?

Maybe I have missed to set this somewhere explicitly? Or the module needs some explicit initialization?

**Comment by ekohl** [comment]
No, this is intended behavior. https://help.ubuntu.com/community/AutomaticSecurityUpdates#Using_the_.22unattended-upgrades.22_package suggests the exact same thing and even states:
> ${distro_id} and ${distro_codename} will be automatically expanded

**Comment by bittner** [comment]
I see. Thanks for the clarification!
