### ISSUE TITLE
Typo - README.md - Reference/options "force_connew"

### ISSUE THREAD

**Issue by 6uhrmittag** [voxpupuli/puppet-unattended_upgrades#109]
File in question: `puppet-unattended_upgrades/README.md`
Line: 162
Solution: `force_connew -> force_confnew`

The documentation contains a typo at
`Reference -> Parameters -> options`
> **force_connew** (false): Always use the new config files, don't prompt

The key is named : `force_confnew`

See: `puppet-unattended_upgrades/manifests/params.pp`
```  $default_options              = { 'force_confdef'        => true,
                                    'force_confold'        => true,
                                    'force_confnew'        => false,
                                    'force_confmiss'       => false, }```

**Comment by ekohl** [comment]
@6uhrmittag would you be be willing to open a PR so you get the proper credits in the history? Github allows you to easily edit files via the web interface and create a PR from that.

**Comment by 6uhrmittag** [comment]
Yes I am!
Thanks for asking @ekohl . This is my first contribution :tada:  
Had no idea how simple it is.


PR: https://github.com/voxpupuli/puppet-unattended_upgrades/pull/117

**Comment by ekohl** [comment]
Congrats. Let's hope it's the first of many.
