### ISSUE TITLE
Allow configuration of Unattended-Upgrade::Sender parameter

### ISSUE THREAD

**Issue by LarsErikP** [voxpupuli/puppet-unattended_upgrades#119]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.5
- Ruby: 2.4.3
- Distribution: Ubuntu 16.04 LTS. 14.04 LTS is not affected, because of the unattended-upgrades package version available in that release.
- Module version: Verfied on both 2.2.0 and 3.1.0

## How to reproduce (e.g Puppet code you use)
N/A
## What are you seeing
There are no parameters to this module, allowing to configure the "Unattended-Upgrade::Sender" paramter, added in this commit: https://github.com/mvo5/unattended-upgrades/commit/cdce03da440c71897b784deb8c5471524928048c (funny thing is - it is not very well documented...)

## What behaviour did you expect instead
The possibility to configure this option.

## Output log
mail returned: 0
smtp-server: 504 5.5.2 <root>: Sender address rejected: need fully-qualified address

## Any additional information you'd like to impart
Of course; this will cause the mails from unattended-upgrades to fail when you try to send e-mail to external addess via an external SMTP server.

**Comment by ekohl** [comment]
That sounds like an easy patch. Could you come up with a PR? I can help you through it if you'd like.

**Comment by LarsErikP** [comment]
Well I could of course give it a try.. :-)

**Comment by LarsErikP** [comment]
So; I gave it a try!
