### ISSUE TITLE
(Confirm) Ubuntu 18.04 support

### ISSUE THREAD

**Issue by mpdude** [voxpupuli/puppet-unattended_upgrades#124]
On Ubuntu 18.04 (with Puppet 5.4.0), I get the following error message in my master's log:

```
(Scope(Class[Unattended_upgrades::Params])) Ubuntu 18.04 "bionic" has reached End of Life - please upgrade!
```

Ubuntu 18.04 is the latest LTS release.

**Comment by ekohl** [comment]
Which version of the module are you using? 3.1.0 should include https://github.com/voxpupuli/puppet-unattended_upgrades/commit/0ce305a0856c318e8813e509e34c4190280138fc.

**Comment by ekohl** [comment]
Looks like I'm already sleeping - we haven't added Bionic to params.pp. The patch should be equal to the one I linked though. A PR would be very welcome.

**Comment by mpdude** [comment]
PR is #125
