### ISSUE TITLE
Support puppetlabs-apt > 5

### ISSUE THREAD

**Issue by mzhaase** [voxpupuli/puppet-unattended_upgrades#133]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Module version: all

Currently this module has a dependency on puppetlabs-apt < 5.0.0. However, latest version is 6.1.1.  It would be nice to support < 7.0.0.

**Comment by dhoppe** [comment]
@mzhaase This issue has been solved by the pull request https://github.com/voxpupuli/puppet-unattended_upgrades/pull/132.
