### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by jhawz** [voxpupuli/puppet-unattended_upgrades#155]
Readme has incorrect key, archive_internal for backup, it should be archive_interval.

**Comment by alexjfisher** [comment]
Would you like to create a Pull Request?

**Comment by jhawz** [comment]
> Would you like to create a Pull Request?

Yes, not sure how yet though.

**Comment by alexjfisher** [comment]
First, fork the repo.  Then, if you're not familiar with git, it should even be possible to edit the file via the github web-interface and create a PR that way.  After editing, choose "Create a new branch for this commit and start a pull request".

**Comment by jhawz** [comment]
Well, looks like I did it right:

https://github.com/voxpupuli/puppet-unattended_upgrades/pull/156

**Comment by alexjfisher** [comment]
Thanks!
For reference, next time, you can link the PR to an issue it fixes.  Then when the PR is merged, the issue will automatically get closed.  See https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
