### ISSUE TITLE
content variable seems like it's required for the init file

### ISSUE THREAD

**Issue by jlove4m** [voxpupuli/puppet-unattended_upgrades#18]
When I try to run this as-is I get:

Error: Must pass content to Apt::Conf[auto-upgrades] at /etc/puppet/modules/unattended_upgrades/manifests/init.pp:63 on node

If I modify it to (adding the content line)
```puppet
  apt::conf { 'auto-upgrades':
    ensure   => absent,
    priority => 20,
    content  => '',
    require  => Package['unattended-upgrades'],
  }
```
It works.

I don't know whether this is something that should be fixed in the apt module since we're doing an "absent" here, but that's what I did in the short term to fix it.

**Comment by igalic** [comment]
in theory, this should be working, according to [apt's source code](https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/conf.pp#L8-L12)

/ping @daenney

**Comment by daenney** [comment]
This shouldn't be needed. As per https://github.com/puppetlabs/puppetlabs-apt/commit/fe609807819cbf8126c3ae43cd96da7a62bce9a7 since apt 2.0.0 up to and including the current version we only care about the content parameter if `ensure` is anything but `absent`.

**Comment by daenney** [comment]
Since we haven't heard back from the reporter and for now I'm convinced this is not an issue as long as you use a recent version of Apt I'm closing this. If this is a problem it should be fixed in Apt as that's where `apt::conf` comes from.
