### ISSUE TITLE
clean key of auto hash not documented

### ISSUE THREAD

**Issue by amateo** [voxpupuli/puppet-unattended_upgrades#24]
According to documentation, valid keys for ```auto``` parameter are ``` fix_interrupted_dpkg```, ```reboot``` and ```remove```, but code also uses the key ```clean``` to configure ```APT::Periodic::AutocleanInterval```.

I guess is should be documented too.

**Comment by daenney** [comment]
This is documented since c8dd1e4d48d509aa921f06.
