### ISSUE TITLE
Example code generates puppet lint error

### ISSUE THREAD

**Issue by sebbASF** [voxpupuli/puppet-unattended_upgrades#247]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

This code (taken from https://forge.puppet.com/modules/puppet/unattended_upgrades/readme#unattended-_-upgrades)

```puppet
class { 'unattended_upgrades':
  origins => [
    'origin=${distro_id},suite=${distro_codename}',
    'origin=${distro_id},suite=${distro_codename}-security',
    'origin=${distro_id},suite=${distro_codename}-backports',
    'origin=${distro_id},suite=${distro_codename}-updates',
  ],
}
```

## What are you seeing

When the code is analysed by puppet-lint, we are seeing the following errors:

Error: single quoted string containing a variable found (check: single_quote_string_with_variables)

## What behaviour did you expect instead

The example code should not cause Puppet-lint to complain.

**Comment by kenyon** [comment]
Yes, you just have to tell puppet-lint to ignore this rule on these lines. A pull request to add the ignore comments to the documentation would be welcome.
