### ISSUE TITLE
Clarify random_sleep documentation

### ISSUE THREAD

**Issue by ffrank** [voxpupuli/puppet-unattended_upgrades#34]
PR #33 introduced a new option that can use some better phrasing in the README docs.

**Comment by fbarbeira** [comment]
Something like this could be valid or is too long?

Random intervall of time (in seconds) that the apt cron job sleeps before the execution. The purpose is to avoid that servers/mirrors get hammered at exactly the same time when a lot of machines are switched on, e.g. 9:00 in the morning. If you don't specify any value, debian/ubuntu use 1800 seconds by default.

**Comment by ffrank** [comment]
I rather like it. "Random intervall of time" is still a little vague though. It should be clear that this the upper boundary for the randomly generated sleep time. (In fact, that is only my assumption so far, because it is not yet properly described anywhere.)
