### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by emning** [voxpupuli/puppet-unattended_upgrades#38]
Would it be possible to do a new release? There are several bugfixes since 1.0.3 that are quite relevant, for instance I just got bitten by the invalid Allowed-Origins lines that was fixed in September (23475aabeff8d2c282efcf8638a66a85c2674b0d).

**Comment by igalic** [comment]
time to [modulesync](https://voxpupuli.org/docs/#publishing-a-module---setup) this module so [anyone can release](https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module)!

**Comment by igalic** [comment]
we've cleaned up the code ( #42 & #43 )
modulesync'ed ( #40 & #41 )
and fixed two issues ( #44 )
prepping a release now! ( #45 )

**Comment by emning** [comment]
You guys rock!

**Comment by igalic** [comment]
\o/

**Comment by daenney** [comment]
It's on the Forge now.
