### ISSUE TITLE
unattended_upgrades module not loading - breaks on Apt::Update dependency

### ISSUE THREAD

**Issue by Wilm0r** [voxpupuli/puppet-unattended_upgrades#48]
It fails to generate the config file, even with me doing a very basic "include unattended_upgrades" without arguments.

```
root@bitlbee:~# puppet agent --test --environment test --trace
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for bitlbee.org
Error: Failed to apply catalog: Could not find dependent Class[Apt::Update] for File[/etc/apt/apt.conf.d/50unattended-upgrades] at /etc/puppet/environments/test/modules/apt/manifests/setting.pp:63
```

I'm not using the apt module much otherwise, except for some pinning tweaks.

**Comment by daenney** [comment]
You have to actually be including the `apt` module in your catalog. It says it can't find `apt::update`, which is part of the Apt module.
