### ISSUE TITLE
Version on Puppet Forge seems to be missing reboot_time parameter in template

### ISSUE THREAD

**Issue by mr-leerkotte** [voxpupuli/puppet-unattended_upgrades#59]
Hello,

The version of this module on puppet forge seems to be missing the reboot_time parameter in the unattended-upgrades.erb template. If i look in the github repo i see this line: `Unattended-Upgrade::Automatic-Reboot-Time "<%= @_auto['reboot_time'].to_s %>";` but this is missing in the version i pulled from puppet forge.

I have reinstalled the module to be sure i had the latest and i still faced the same problem, i can work around the problem by manually adding the option but i just wanted to let you guys know about this issue.

**Comment by bastelfreak** [comment]
Hi,
I'm currently doing a new release in https://github.com/voxpupuli/puppet-unattended_upgrades/pull/60

**Comment by juniorsysadmin** [comment]
Fixed in #60
