### ISSUE TITLE
Not setting up a daily cron

### ISSUE THREAD

**Issue by spengilley** [voxpupuli/puppet-unattended_upgrades#87]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.7
- Ruby:     2.1.5p273
- Distribution: Deb Jessie
- Module version: Latest

## How to reproduce (e.g Puppet code you use)
class { 'unattended_upgrades':
        require => Class['apt']
    }
## What are you seeing
nothing related to unattended upgrades in /etc/cron.daily

## What behaviour did you expect instead
A file in /etc/cron.daily and security updates installed when daily cron runs

## Output log
No logs created for unattended upgrades

**Comment by ffrank** [comment]
Hi, thanks for reaching out.

As per [StackExchange](https://unix.stackexchange.com/questions/342663/who-starts-unattended-upgrades/342681), apt does not in fact rely on cron to perform periodic updates.

Would it be alright if I close this as "won't fix"?

**Comment by spengilley** [comment]
Hey mate

Yes that would be absolutely fine
