### ISSUE TITLE
Error when configuring unattended-upgrades

### ISSUE THREAD

**Issue by htj** [voxpupuli/puppet-unattended_upgrades#92]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.0
- Distribution: Ubuntu 16.04
- Module version: 2.2.1-rc0 (latest git version as of 20170511)

## How to reproduce (e.g Puppet code you use)

I have this one:

class { 'unattended_upgrades':
  auto => { 'remove' => true },
}

And feed it into puppet. I get the same error with 2.2.0 (after hacking the apt depdency version)

I get the same version without auto remove.

## What are you seeing

root@cctest2:/var/opt# puppet apply < /etc/puppet/manifests/unattended-upgrades.pp 
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/apt/manifests/setting.pp", 21]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: Unknown variable: '::apt::config_files'. at /etc/puppetlabs/code/environments/production/modules/apt/manifests/setting.pp:34:12
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Operator '[]' is not applicable to an Undef Value. at /etc/puppetlabs/code/environments/production/modules/apt/manifests/setting.pp:34:12  at /etc/puppetlabs/code/environments/production/modules/apt/manifests/conf.pp:15 on node cctest2

Not entirely sure if this is an error in the apt package (I am using 4.0.0) or unattended-upgrades, but it triggers with unattende-upgrades.

**Comment by jarekherisz** [comment]
I fix it by add to file 
unattended_upgrades\manifests\init.pp
In line 23 
`contain apt`

Reason of error

>  Unknown variable: '::apt::config_files'

 is that class is not exists and module can try use it value.

**Comment by htj** [comment]
Thanks. I don't fully understand this (new to puppet), but it seems to work. Will make pull request.

**Comment by petems** [comment]
Fixed via #103
