### ISSUE TITLE
License in metadata.json doesn't match the dual licensing documented in the README.

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-unattended_upgrades#93]
metadata.json says 'Apache-2.0' but the README says part of the code (stuff derived from https://github.com/evolvingweb/puppet-apt/??) is MIT.

**Comment by DavidS** [comment]
Apparently this was relicensed when the company took over maintainership (see https://github.com/puppetlabs/puppetlabs-apt/commit/245b2b178378c3783cf31348e24034b8d195a68f and https://github.com/puppetlabs/puppetlabs-apt/commit/08c1283437e2a7072e788f489f1de73dbc9a6c5d).

**Comment by ekohl** [comment]
Is this still an active issue? Does metadata.json even allow specifying a dual license?

**Comment by alexjfisher** [comment]
@ekohl It doesn't.

**Comment by ekohl** [comment]
Then given the current description I think the status is good enough but IANAL.

**Comment by anarcat** [comment]
okay, let's just live with this until a copyright holder actually complains.
